"""initial_schema_tb_012

Revision ID: 49ae8e2643e7
Revises: 
Create Date: 2026-03-12 17:33:30.942777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ae8e2643e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('logs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('full_tuition', sa.Float(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('scholarship_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('import_batches')
    op.drop_table('financial_transactions')
    # ### end Alembic commands ###
