"""add_audit_columns_to_students_and_batches

Revision ID: 64d41a2e434e
Revises: 49ae8e2643e7
Create Date: 2026-03-12 21:57:24.359395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d41a2e434e'
down_revision: Union[str, Sequence[str], None] = '49ae8e2643e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'import_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'batch_id')
    op.drop_column('import_batches', 'row_count')
    # ### end Alembic commands ###
